/* ===================================================
   Spark Course Advisor — Course Catalogue
   Verified, Audit-Grade Data from Apex SkillsBuild Audit
   =================================================== */

const COURSE_CATALOGUE = [
    { id: "C001", name: "Introduction to Large Language Models", jtbd: "Job A", market: "AI Leadership / McKinsey", readiness: "GREEN", tags: ["AI-CORE", "GENAI"], complexity: "BEGINNER", credential: false },
    { id: "C002", name: "Mastering the Art of Prompting", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "GREEN", tags: ["GENAI", "PRODUCT"], complexity: "BEGINNER", credential: false },
    { id: "C003", name: "Introduction to Artificial Intelligence", jtbd: "Job A", market: "AI Leadership / McKinsey", readiness: "GREEN", tags: ["AI-CORE"], complexity: "BEGINNER", credential: false },
    { id: "C004", name: "Large Language Model Basics", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "BROWN", tags: ["GENAI", "AI-CORE"], complexity: "BEGINNER", credential: false },
    { id: "C005", name: "Craft Precise Prompts for AI Models", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "GREEN", tags: ["GENAI", "PRODUCT"], complexity: "BEGINNER", credential: true },
    { id: "C006", name: "Risk Management and Fraud Detection using Generative AI", jtbd: "Job A", market: "AI Leadership / McKinsey", readiness: "GREEN", tags: ["AI-CORE", "BUSINESS"], complexity: "ADVANCED", credential: false },
    { id: "C007", name: "Elevate Education with AI", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "GREEN", tags: ["AI-CORE", "PRODUCT"], complexity: "BEGINNER", credential: false },
    { id: "C008", name: "The Power of Personalized Finance with AI", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "GREEN", tags: ["BUSINESS", "AI-CORE"], complexity: "INTERMEDIATE", credential: false },
    { id: "C009", name: "Getting Started with Data", jtbd: "Job B", market: "Data-Driven / BCG", readiness: "GREEN", tags: ["DATA"], complexity: "BEGINNER", credential: true },
    { id: "C010", name: "Artificial Intelligence Practitioner Pathway", jtbd: "Job A", market: "AI Leadership / McKinsey", readiness: "GREEN", tags: ["AI-CORE"], complexity: "ADVANCED", credential: true, credentialLabel: "7 microcredentials" },
    { id: "C011", name: "Data Analytics Fluency Pathway", jtbd: "Job B", market: "Data-Driven / BCG", readiness: "GREEN", tags: ["DATA"], complexity: "ADVANCED", credential: true, credentialLabel: "6 microcredentials" },
    { id: "C012", name: "Generative AI Essentials: Using LLMs to Work with Data", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "GREEN", tags: ["GENAI", "DATA"], complexity: "INTERMEDIATE", credential: true },
    { id: "C013", name: "Enterprise Data Science in Practice", jtbd: "Job A", market: "AI Leadership / McKinsey", readiness: "GREEN", tags: ["DATA", "CODE"], complexity: "ADVANCED", credential: false },
    { id: "C014", name: "Building Trustworthy AI Enterprise Solutions", jtbd: "Job A", market: "AI Leadership / McKinsey", readiness: "GREEN", tags: ["AI-CORE", "BUSINESS"], complexity: "INTERMEDIATE", credential: false },
    { id: "C015", name: "AI Fundamentals: Language and Vision in AI", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "GREEN", tags: ["AI-CORE"], complexity: "BEGINNER", credential: true },
    { id: "C016", name: "Make Agentic AI Work for You", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "GREEN", tags: ["AI-CORE", "PRODUCT"], complexity: "INTERMEDIATE", credential: true },
    { id: "C017", name: "Building AI Solutions Using Advanced Algorithms and Open Source Frameworks", jtbd: "Job A", market: "AI Leadership / McKinsey", readiness: "GREEN", tags: ["AI-CORE", "CODE"], complexity: "ADVANCED", credential: false },
    { id: "C018", name: "Intelligent by Design: Build an AI Agent", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "GREEN", tags: ["AI-CORE", "CODE"], complexity: "ADVANCED", credential: true },
    { id: "C019", name: "Level Up Cybersecurity with Generative AI", jtbd: "Job B", market: "Data-Driven / BCG", readiness: "GREEN", tags: ["CYBER", "AI-CORE"], complexity: "INTERMEDIATE", credential: false },
    { id: "C020", name: "AI Fundamentals: Foundations for Understanding AI", jtbd: "Job A", market: "AI Leadership / McKinsey", readiness: "GREEN", tags: ["AI-CORE"], complexity: "BEGINNER", credential: true },
    { id: "C021", name: "Prompting Techniques for Classification and Summarization Tasks Using IBM Granite", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "GREEN", tags: ["GENAI", "CODE"], complexity: "INTERMEDIATE", credential: true },
    { id: "C022", name: "AI Literacy", jtbd: "Job A", market: "AI Leadership / McKinsey", readiness: "GREEN", tags: ["AI-CORE"], complexity: "BEGINNER", credential: true },
    { id: "C023", name: "Retrieval-Augmented Generation for Enhanced AI Outputs", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "BROWN", tags: ["AI-CORE", "GENAI"], complexity: "ADVANCED", credential: true },
    { id: "C024", name: "Turn Ideas Into Prototypes With Vibe Coding", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "GREEN", tags: ["CODE", "PRODUCT"], complexity: "INTERMEDIATE", credential: false },
    { id: "C025", name: "The Rise of Multiagent Systems", jtbd: "Job A", market: "AI Leadership / McKinsey", readiness: "GREEN", tags: ["AI-CORE", "CODE"], complexity: "ADVANCED", credential: false },
    { id: "C026", name: "Build Smarter AI with Embeddings", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "BROWN", tags: ["AI-CORE", "CODE"], complexity: "ADVANCED", credential: false },
    { id: "C027", name: "Summarizing Data Using IBM Granite", jtbd: "Job B", market: "Data-Driven / BCG", readiness: "GREEN", tags: ["DATA", "GENAI"], complexity: "INTERMEDIATE", credential: false },
    { id: "C028", name: "Build Your First Chatbot", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "GREEN", tags: ["CODE", "GENAI"], complexity: "INTERMEDIATE", credential: false },
    { id: "C029", name: "Coding Simplified with Generative AI", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "GREEN", tags: ["CODE", "GENAI"], complexity: "INTERMEDIATE", credential: false },
    { id: "C030", name: "Explore Text to Speech Using IBM Watson", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "GREEN", tags: ["AI-CORE", "PRODUCT"], complexity: "BEGINNER", credential: false },
    { id: "C031", name: "Retrieval-Augmented Generation for Enhanced AI Outputs (Module)", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "BROWN", tags: ["AI-CORE", "GENAI"], complexity: "INTERMEDIATE", credential: false },
    { id: "C032", name: "Getting Started with Generative AI", jtbd: "Job A", market: "AI Leadership / McKinsey", readiness: "GREEN", tags: ["GENAI"], complexity: "BEGINNER", credential: true },
    { id: "C033", name: "Prompt Engineering: Shaping Better AI Responses", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "GREEN", tags: ["GENAI", "PRODUCT"], complexity: "INTERMEDIATE", credential: false },
    { id: "C034", name: "Use Generative AI for Software Development", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "GREEN", tags: ["CODE", "GENAI"], complexity: "INTERMEDIATE", credential: false },
    { id: "C035", name: "Unleashing the Power of AI Agents", jtbd: "Job A", market: "AI Leadership / McKinsey", readiness: "GREEN", tags: ["AI-CORE", "CODE"], complexity: "ADVANCED", credential: false },
    { id: "C036", name: "Supercharge Your Data Analytics with Generative AI", jtbd: "Job B", market: "Data-Driven / BCG", readiness: "GREEN", tags: ["DATA", "GENAI"], complexity: "INTERMEDIATE", credential: false },
    { id: "C037", name: "Using Prompting Techniques to Organize a Daily Work and Personal Routine", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "GREEN", tags: ["GENAI", "PRODUCT"], complexity: "BEGINNER", credential: false },
    { id: "C038", name: "AI for Sustainability", jtbd: "Job B", market: "Sustainability / McKinsey", readiness: "GREEN", tags: ["SUSTAIN", "AI-CORE"], complexity: "INTERMEDIATE", credential: true },
    { id: "C039", name: "Vector Embeddings: AI's Key to Meaning", jtbd: "Job A", market: "AI Leadership / McKinsey", readiness: "BROWN", tags: ["AI-CORE", "CODE"], complexity: "ADVANCED", credential: false },
    { id: "C040", name: "AI in Legal: From Research to Results", jtbd: "Job A", market: "AI Leadership / McKinsey", readiness: "GREEN", tags: ["BUSINESS", "AI-CORE"], complexity: "ADVANCED", credential: false },
    { id: "C041", name: "AI in Healthcare: Improving Care and Efficiency", jtbd: "Job A", market: "AI Leadership / McKinsey", readiness: "GREEN", tags: ["BUSINESS", "AI-CORE"], complexity: "ADVANCED", credential: false },
    { id: "C042", name: "Crafting Precision Prompts with Generative AI", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "GREEN", tags: ["GENAI", "PRODUCT"], complexity: "INTERMEDIATE", credential: false },
    { id: "C043", name: "Craft Precise Prompts for AI Models (Module)", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "GREEN", tags: ["GENAI", "AI-CORE"], complexity: "INTERMEDIATE", credential: false },
    { id: "C044", name: "Interacting with AI", jtbd: "Job A", market: "AI Leadership / McKinsey", readiness: "GREEN", tags: ["AI-CORE"], complexity: "BEGINNER", credential: false },
    { id: "C045", name: "Introduction to Retrieval Augmented Generation", jtbd: "Job A", market: "AI Leadership / McKinsey", readiness: "BROWN", tags: ["AI-CORE", "GENAI"], complexity: "INTERMEDIATE", credential: false },
    { id: "C046", name: "Data Fundamentals", jtbd: "Job A", market: "AI Leadership / McKinsey", readiness: "GREEN", tags: ["DATA"], complexity: "BEGINNER", credential: true },
    { id: "C047", name: "AI's New Superpower: Multimodal Retrieval-Augmented Generation", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "BROWN", tags: ["AI-CORE", "GENAI"], complexity: "ADVANCED", credential: false },
    { id: "C048", name: "Classifying Data Using IBM Granite", jtbd: "Job B", market: "Data-Driven / BCG", readiness: "GREEN", tags: ["DATA", "CODE"], complexity: "INTERMEDIATE", credential: false },
    { id: "C049", name: "IBM Granite Models for Software Development", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "GREEN", tags: ["CODE", "AI-CORE"], complexity: "ADVANCED", credential: false },
    { id: "C050", name: "Using Prompt Writing Techniques to Craft a LinkedIn Profile", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "GREEN", tags: ["GENAI", "PRODUCT"], complexity: "BEGINNER", credential: false },
    { id: "C051", name: "Generative AI in Action", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "GREEN", tags: ["GENAI", "AI-CORE"], complexity: "INTERMEDIATE", credential: true },
    { id: "C052", name: "Getting Started with Artificial Intelligence", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "GREEN", tags: ["AI-CORE"], complexity: "BEGINNER", credential: false },
    { id: "C053", name: "Ethical Considerations for Generative AI", jtbd: "Job A", market: "AI Leadership / McKinsey", readiness: "GREEN", tags: ["AI-CORE", "BUSINESS"], complexity: "INTERMEDIATE", credential: false },
    { id: "C054", name: "Machine Learning for Data Science Projects", jtbd: "Job B", market: "Data-Driven / BCG", readiness: "GREEN", tags: ["DATA", "CODE"], complexity: "ADVANCED", credential: false },
    { id: "C055", name: "Artificial Intelligence Fundamentals", jtbd: "Job A", market: "AI Leadership / McKinsey", readiness: "GREEN", tags: ["AI-CORE"], complexity: "BEGINNER", credential: true },
    { id: "C056", name: "Cybersecurity Fluency Pathway", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "GREEN", tags: ["CYBER"], complexity: "ADVANCED", credential: true, credentialLabel: "6 microcredentials" },
    { id: "C057", name: "Getting Started with Threat Intelligence and Hunting", jtbd: "Job A", market: "AI Leadership / McKinsey", readiness: "GREEN", tags: ["CYBER"], complexity: "INTERMEDIATE", credential: false },
    { id: "C058", name: "Getting Started with Cybersecurity", jtbd: "Job A", market: "AI Leadership / McKinsey", readiness: "GREEN", tags: ["CYBER"], complexity: "BEGINNER", credential: true },
    { id: "C059", name: "Security Operations Center in Practice", jtbd: "Job A", market: "AI Leadership / McKinsey", readiness: "GREEN", tags: ["CYBER"], complexity: "ADVANCED", credential: false },
    { id: "C060", name: "Enterprise Security in Practice", jtbd: "Job A", market: "AI Leadership / McKinsey", readiness: "GREEN", tags: ["CYBER"], complexity: "ADVANCED", credential: false },
    { id: "C061", name: "Cybersecurity Fundamentals", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "GREEN", tags: ["CYBER"], complexity: "BEGINNER", credential: true },
    { id: "C062", name: "Transforming the Sports Fan Experience with AI", jtbd: "Job C", market: "AI Product Manager / WEF", readiness: "GREEN", tags: ["AI-CORE", "PRODUCT"], complexity: "BEGINNER", credential: false },
];

/* ─── Tag Mapping for subject interest ─── */
const SUBJECT_TAG_MAP = {
    "ai": ["AI-CORE"],
    "artificial intelligence": ["AI-CORE"],
    "machine learning": ["AI-CORE", "CODE"],
    "ml": ["AI-CORE", "CODE"],
    "data": ["DATA"],
    "analytics": ["DATA"],
    "data science": ["DATA", "CODE"],
    "statistics": ["DATA"],
    "cybersecurity": ["CYBER"],
    "security": ["CYBER"],
    "cyber": ["CYBER"],
    "hacking": ["CYBER"],
    "product": ["PRODUCT"],
    "design": ["PRODUCT"],
    "ux": ["PRODUCT"],
    "user experience": ["PRODUCT"],
    "sustainability": ["SUSTAIN"],
    "esg": ["SUSTAIN"],
    "environment": ["SUSTAIN"],
    "climate": ["SUSTAIN"],
    "coding": ["CODE"],
    "programming": ["CODE"],
    "software": ["CODE"],
    "dev": ["CODE"],
    "development": ["CODE"],
    "business": ["BUSINESS"],
    "strategy": ["BUSINESS"],
    "finance": ["BUSINESS"],
    "management": ["BUSINESS"],
    "prompting": ["GENAI"],
    "genai": ["GENAI"],
    "generative ai": ["GENAI"],
    "llm": ["GENAI"],
    "chatbot": ["GENAI", "CODE"],
    "chatbots": ["GENAI", "CODE"],
    "agent": ["AI-CORE", "CODE"],
    "agents": ["AI-CORE", "CODE"],
};

/* ─── Education Level → Complexity Tier ─── */
const EDUCATION_COMPLEXITY_MAP = {
    "first year": "BEGINNER",
    "freshman": "BEGINNER",
    "1st year": "BEGINNER",
    "second year": "BEGINNER-INTERMEDIATE",
    "sophomore": "BEGINNER-INTERMEDIATE",
    "2nd year": "BEGINNER-INTERMEDIATE",
    "third year": "INTERMEDIATE-ADVANCED",
    "junior": "INTERMEDIATE-ADVANCED",
    "3rd year": "INTERMEDIATE-ADVANCED",
    "senior": "INTERMEDIATE-ADVANCED",
    "fourth year": "INTERMEDIATE-ADVANCED",
    "4th year": "INTERMEDIATE-ADVANCED",
    "final year": "INTERMEDIATE-ADVANCED",
    "postgraduate": "ADVANCED",
    "masters": "ADVANCED",
    "master's": "ADVANCED",
    "phd": "ADVANCED",
    "graduate": "ADVANCED",
    "postgrad": "ADVANCED",
    "other": "BEGINNER-INTERMEDIATE",
};
